-- +goose Up
ALTER TABLE orders ADD COLUMN IF NOT EXISTS is_cross_city BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS surcharge_amount INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS surcharge_percent INTEGER NOT NULL DEFAULT 0;

-- +goose Down
ALTER TABLE orders DROP COLUMN IF EXISTS surcharge_percent;
ALTER TABLE orders DROP COLUMN IF EXISTS surcharge_amount;
ALTER TABLE orders DROP COLUMN IF EXISTS is_cross_city;
